### ISSUE TITLE
Index and thumbnails tabs

### ISSUE THREAD

**Issue by mariobernardes** [Daniel-KM/UniversalViewer4Omeka#12]
Hello again,

When I open the uv in the collection view, the thumbnails tab is shown as default.
How can I configure uv in order to show the index tab as default when opened?
Thanks,
Mario

**Comment by Daniel-KM** [comment]
Hi,

I don't know which is the name of the option, but you can test any config in http://universalviewer.io/examples/ (currently the online config is unavailable, see https://github.com/UniversalViewer/universalviewer/wiki/Configuration) and check the option for the left panel, then save the config.json in your theme (themes/My_Theme/universal-viewer/config.json). 

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mariobernardes** [comment]
Hello Daniel,

The path for config.json is: /var/www/html/omeka/plugins/UniversalViewer/views/public/universal-viewer/config.json.
To test, I tried to hide the left panel setting leftPanelEnabled to false, but it didn’t work.
Am I editing the correct file?
Thanks,
Mario

**Comment by Daniel-KM** [comment]
Hi,

Yes, this is the good file, but it's recommended to copy it in themes/My_Theme/universal-viewer/config.json to avoid to overwrite it when there is an update. I don't understand why it doesn't load, perhaps a cache issue. Empty it or try with another browser.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mariobernardes** [comment]
Hello,

Do you mean that I should copy the file omeka/plugins/UniversalViewer/views/public/universal-viewer/config.json to themes/My_Theme/universal-viewer/config.json? The directory universal-viewer does not exist under My_Theme (Berlin). 


When trying to make appear by default the Index tab in the front the of the thumbnails, I saw there is an attribute in contentLeftPanel Option named tabOrder. What values are possible for tabOrder?

Thanks again for your time,

Mario

**Comment by Daniel-KM** [comment]
Hi,

Yes, you have to create manually the folder "universal-viewer" in your theme (and set its rights) and put the config.json inside. This is the best way to customize your views instead of modify the files inside the plugins. 

UniversalViewer 4 Omeka is just a plugin that integrates the widget UniversalViewer inside Omeka, without any change. So, for such queries, it's better to ask the author of the widget at https://github.com/UniversalViewer/universalviewer.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by mariobernardes** [comment]
Ok.
Thanks anyway,
Mario
