### ISSUE TITLE
Enabling HTML in right-hand panel (information)?

### ISSUE THREAD

**Issue by marianiku** [Daniel-KM/UniversalViewer4Omeka#4]
Hi,

Am I understanding correctly that the right-hand panel of the plugin (information) allows text only or does HTML need to be enabled somewhere? I've HTML enabled in some item fields, but the plugin ignores the tags. These are basic tags (paragraph, span etc) with the occasional css style (underline, text color etc). Thanks.

**Comment by Daniel-KM** [comment]
Hi,

This is a question partly related to the integration in Omeka too. In fact, currently, Omeka sends value of elements to the viewer as it, and even doesn't check if this is html or not, because commonly, the records are without html. I can modify easily the plugin to purge the html tags, but to manage the html by the viewer is a question related to the viewer itself, so it may be asked on https://github.com/UniversalViewer/universalviewer. 

For css, you can modify them in the themes (views/shared/javascripts/uv/themes) and in the config.json files (in views/public/universal-viewer and in views/shared/javascripts/uv/lib).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by marianiku** [comment]
Hi,

Many thanks for the response. Troubling you just a little further with a follow-up question: I since saw that it works fine if define a style in the Universal Viewer css file for, say, all span elements in the item metadata field. However, it does not work if I identify a specific span element in the metadata field with an id or a class name and then define a style for that in the UV css file. Is this likely to be something to do with Omeka (like perhaps external css is not supported in the metadata field) or with Universal Viewer? Again many thanks.

**Comment by Daniel-KM** [comment]
Hi,

Furthermore, there is no check on css files. As long as they are loaded by the browser, they are supported. You just need to check the order of css rules.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by marianiku** [comment]
Hi,

Many thanks for your replies. I since discovered that UniversalViewer strips HTML attributes such as style, id and class from the metadata in the manifest.json file, according to the limitation in the IIIF Presentation API. Our idea was to encode the critical apparatus in our transcriptions with HTML for display purposes (our metadata and transcriptions are in TEI encoded xml, but the options for displaying this in Omeka are very limited). While it is easy to add the attributes to the list of allowed HTML elements and attributes in the UniversalViewer code, the limitation is there to prevent HTML and script injection attacks. Would you be able to say whether this is a real danger with the style/id/class attributes in this particular case, where UniversalViewer receives the data for display from Omeka? Again many thanks.

**Comment by Daniel-KM** [comment]
Hi,

I don't think there is a danger with basic standard html tags used to display text. You can ask on the UniversalViewer page if there is an option to allow a list of defined tags (or a new feature for that).

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
