### ISSUE TITLE
Make UV to use Omeka base_root?

### ISSUE THREAD

**Issue by ta1986** [Daniel-KM/UniversalViewer4Omeka#7]
Could you show how to enforce ssl for Universal Viewer? My Omeka $base_root is in https but UV always request resources/manifests in http. Thanks.

**Comment by Daniel-KM** [comment]
Hi,

The plugin only uses standard methods of Omeka, standard routes, relative urls and the standard web_root. Have you set ssl in `application/config/config.ini` : `ssl = "always"`?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by ta1986** [comment]
Thanks for your response. We redirect to https in LTM (local traffic manager) box, so I can't set ssl = "always" in localhost. It will cause infinite redirect. Instead, I "enforce" $base_root in bootstrap.php to https only. I know this is not recommended but Omeka works fine so far.

Sounds like UV plugin rely on Omeka for SSL redirect. Is it possible to overwrite web_root to https in UV plugin? Thanks.

**Comment by Daniel-KM** [comment]
Hi,

The plugin uses the standard routing system of Omeka and Zend and it uses the function `absolute_url()` in the file applications/libraries/globals.php when an absolute link is required. You can change it to your needs (or the Zend_View_Helper_ServerUrl). 

Note that this type of change inside the core is not recommended, because it makes the system harder to maintain, so it should be very limited and well documented.

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management

**Comment by ta1986** [comment]
Great, I will test that approach. Thanks for your help.
